<a href="https://colab.research.google.com/github/Chris-Goyette/colab_practice/blob/main/Numpy_Array_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1+2

3

In [ ]:
2+2

4

In [ ]:
import sys
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
print(a)


[1 2 3 4]


In [ ]:
print(a[0])

1


In [ ]:
a[0]

1

##numpy arrays are immutable...I think
###This means that if you conduct an operation on the the array it will show you what it looks like but the actual structure will be the same. 

In [ ]:
a = np.arange(5)

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a+20)

[20 21 22 23 24]


In [ ]:
print(a)


[0 1 2 3 4]
