<a href="https://colab.research.google.com/github/Chris-Goyette/colab_practice/blob/main/notebooks/Numpy_Array_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

##numpy arrays are mutable, but only when you assign it to new values
### Otherwise the changes you made won't take effect. 


In [10]:
a = np.arange(5)

In [11]:
print(a)

[0 1 2 3 4]


In [12]:
type(a)

numpy.ndarray

In [13]:
print(a+20)

[20 21 22 23 24]


In [14]:
print(a)


[0 1 2 3 4]


## The Basics

In [16]:
#Create a Numpy Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [33]:
print(type(a))

<class 'numpy.ndarray'>


In [25]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [30]:
# Get Dimensions
print(a.ndim)
print(b.ndim)


1
2


In [32]:
# Get the shape
# The shape property will return the number of rows by columns 
# The shape of a 1-dimensional array is a vector, which is why you don't see another number in the first example.  
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [35]:
# Get Type
print(a.dtype)
print(b.dtype)

int64
int64


In [37]:
# Get the length of one array element in bytes.
print(a.itemsize)
print(b.itemsize)

8
8


In [40]:
# Get total size of the array in bytes
print(a.nbytes)
print(b.nbytes)

24
48


In [41]:
# Get the number of elements
print(a.size)
print(b.size)

3
6


## Accessing / Changing specific elements, rows, columns, etc. 

In [43]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
# Get specific elements [row, column]
# The syntax is arra[row, column :step]
a[1,-3:]

array([12, 13, 14])

In [48]:
print(a[1, -3:])

[12 13 14]


In [49]:
# Get a specific column 
print(a[:, 2])

[ 3 10]


In [51]:
# Getting fancy with step
# I am returning rows 0 and 1, column 2 through the end, stepping by 2
print(a[:, 2: :2])

[[ 3  5  7]
 [10 12 14]]


## 3 Dimensional Array

In [60]:
three_dimensions = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_dimensions)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
# Get specific element (work outside in)
print(three_dimensions[0, 1, 1])

4


In [64]:
# Replace the following values in the three dimensional array: 
three_dimensions[:,1,:]

array([[3, 4],
       [7, 8]])

In [66]:
# With this: 
new_data = np.array([[1,2],[3,4]])
new_data

array([[1, 2],
       [3, 4]])

In [67]:
three_dimensions[:,1,:] = new_data
three_dimensions

array([[[1, 2],
        [1, 2]],

       [[5, 6],
        [3, 4]]])

## Examples of some cool things you can do
- You can havd a 2 dimensional array with the dimensions of 7 by 7 and and prefill the values with zeros, ones, or random digits. 
- You can also select a portion of that 2 dimensional array and update it. 

In [5]:

seven_by_seven = np.zeros((7,7))
five_by_five = np.ones((5,5))
print(seven_by_seven)
print(five_by_five)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
seven_by_seven[1:6,1:6] = five_by_five
print(seven_by_seven)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## You can perform element wise arithmetic
- This basically means you can do math to each element in an array

In [13]:
# Add two arrays together, element wise
group_1 = np.array([1,1,1,1])
group_2 = np.array([2,2,2,2])

print(group_1 + group_2)

# Other basic math 
print(group_1 + 5)
print(group_1 * 10)
print(np.cos(group_1))

[3 3 3 3]
[6 6 6 6]
[10 10 10 10]
[0.54030231 0.54030231 0.54030231 0.54030231]


## Linear Algebra


In [21]:
# Matrix Multiplication

data_1 = np.ones((2,3))
data_2 = np.full((3,2), 2)

print('First data set:')
print(data_1)
print('Second data set:')
print(data_2)
print('Matrices multiplied together:')
print(np.matmul(data_1, data_2))

First data set:
[[1. 1. 1.]
 [1. 1. 1.]]
Second data set:
[[2 2]
 [2 2]
 [2 2]]
Matrices multiplied together:
[[6. 6.]
 [6. 6.]]


## Statistics

In [26]:
#min, max, mean, etc. 

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
print(stats.min())
print(stats.max())
print(stats.mean())


1
6
3.5


In [35]:
print(np.min(stats))
print(np.max(stats))
print(np.mean(stats))

1
6
3.5


In [38]:
# You can also specify the axis so that you can narrow where you want to perform these functions
print(stats)

[[1 2 3]
 [4 5 6]]


In [41]:
# axis=0 means numpy will perform computations vertically 
np.max(stats, axis=0)

array([4, 5, 6])

In [42]:
# axis=1 means numpy will perform computations horizontally. 

np.max(stats, axis=1)

array([3, 6])

In [43]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [44]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
print('The dimensions are:')
print(before.shape)

The dimensions are:
(2, 4)


In [56]:
after = before.reshape(4, 2)
print(after)
print('The dimensions are now:')
print(after.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
The dimensions are now:
(4, 2)


## Miscellaneous

In [64]:
# Load data from file to a numpy array
filedata = np.genfromtxt('random_data.txt', delimiter=',') 
# Then convert the type from float to int
filedata = filedata.astype('int32')
filedata

OSError: ignored

## Boolean Masking and Advanced Indexing 

In [67]:
random_data = np.full((10,10), 2)
random_data

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [71]:
random_data_2 = random.randint(11, size=(10,10))
random_data_2

array([[ 1,  8,  9,  6,  4, 10,  5,  5,  9,  8],
       [ 0,  8,  8,  3,  6,  5,  8, 10,  7,  5],
       [ 1,  8,  9,  2,  6,  6,  5,  5,  0,  7],
       [ 5, 10,  4,  3, 10,  4,  3,  7,  8,  3],
       [ 1,  6,  8,  0,  2,  8,  4,  5,  1,  3],
       [ 2,  5,  7,  9,  2,  8, 10,  8,  6,  3],
       [ 5,  8,  8,  1,  2,  9,  6,  1,  0,  9],
       [ 7,  0,  4,  5,  8, 10,  8,  0,  7,  4],
       [ 6,  7,  5,  8,  9,  2,  0,  9,  7,  9],
       [ 4, 10,  6,  6,  2,  1,  0,  5,  2,  7]])

In [72]:
random_data_2 > 5

array([[False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [False,  True,  True, False,  True, False,  True,  True,  True,
        False],
       [False,  True,  True, False,  True,  True, False, False, False,
         True],
       [False,  True, False, False,  True, False, False,  True,  True,
        False],
       [False,  True,  True, False, False,  True, False, False, False,
        False],
       [False, False,  True,  True, False,  True,  True,  True,  True,
        False],
       [False,  True,  True, False, False,  True,  True, False, False,
         True],
       [ True, False, False, False,  True,  True,  True, False,  True,
        False],
       [ True,  True, False,  True,  True, False, False,  True,  True,
         True],
       [False,  True,  True,  True, False, False, False, False, False,
         True]])

In [86]:
# You can index by passing in a list
# For example, you only want to display values that are true
# This is like filtering through your data
results = random_data_2[random_data_2 > 5]
results

array([ 8,  9,  6, 10,  9,  8,  8,  8,  6,  8, 10,  7,  8,  9,  6,  6,  7,
       10, 10,  7,  8,  6,  8,  8,  7,  9,  8, 10,  8,  6,  8,  8,  9,  6,
        9,  7,  8, 10,  8,  7,  6,  7,  8,  9,  9,  7,  9, 10,  6,  6,  7])

In [87]:
# If you want to perform the track vertically then you will want to use np.any()
np.all(results > 8, axis= 0)

False